version: 2
jobs:
  build:
    general:
      branches:
        ignore:
          - /\/.*/
    working_directory: ~/circleci-demo-java-spring
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: cache-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/Shopping-Basket-0.0.1-SNAPSHOT.jar